# -*- coding: utf-8 -*-
"""57785_lab9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWjDoT55Safl9jO7i_YJIkNYoRRkHB0p
"""

# Zadanie nr 1 i 2

import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
from sklearn.neighbors import KDTree

class KNN:
    def __init__(self, n_neighbors=1, use_KDTree=False):
        self.n_neighbors = n_neighbors
        self.use_KDTree = use_KDTree

    def fit(self, X, y):
        self.X = X
        self.y = y
        if self.use_KDTree:
            self.tree = KDTree(X)


    def predict(self, X):
        y_pred = []
        is_classification = np.issubdtype(self.y.dtype, np.integer)

        for x in X:

            if self.use_KDTree:
                            dist, ind = self.tree.query(x.reshape(1, -1), k=self.n_neighbors)
                            labels = self.y[ind[0]]

            distances = []

            # liczenie odległości
            for i in range(len(self.X)):
                d = np.linalg.norm(x - self.X[i])
                distances.append((d, self.y[i]))

            # sortowanie po dystansie
            distances.sort(key=lambda x: x[0])

            # wybór k sąsiadów
            neighbors = distances[:self.n_neighbors]
            labels = [neighbor[1] for neighbor in neighbors]

            # klasyfikacja
            if is_classification:
                pred = np.bincount(labels).argmax()
            # regresja
            else:
                pred = np.mean(labels)

            y_pred.append(pred)

        return np.array(y_pred)

    def score(self, X, y):
        y_pred = self.predict(X)

        # klasyfikacja
        if np.issubdtype(y.dtype, np.integer):
            return np.mean(y_pred == y)
        # regresja
        else:
            return np.mean((y_pred - y) ** 2)

# Zadanie nr 3

from sklearn import datasets
X, y = datasets.make_classification(
    n_samples=100,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_repeated=0,
    random_state=3
)

# model
knn_model = KNN()
knn_model.fit(X, y)

# siatka
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

xx, yy = np.meshgrid(
    np.linspace(x_min, x_max, 300),
    np.linspace(y_min, y_max, 300)
)

# predykcja
grid = np.c_[xx.ravel(), yy.ravel()]
Z = knn_model.predict(grid)
Z = Z.reshape(xx.shape)

# wykres
plt.figure(figsize=(7,5))

# kolorowe tło
plt.contourf(xx, yy, Z, cmap="viridis", alpha=0.3)

# granice (linie jak na obrazku)
plt.contour(xx, yy, Z, colors='green', linewidths=2)

# punkty
plt.scatter(X[:, 0], X[:, 1], c=y, cmap="viridis", edgecolor='k')

plt.title("random data")
plt.xlabel("x1")
plt.ylabel("x2")
plt.show()

# Zadanie nr 4

from sklearn import datasets
from sklearn.decomposition import PCA

iris = datasets.load_iris()
X = iris.data
Y = iris.target

# PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# KNN (na 4D!)
knn_model = KNN(n_neighbors=5)
knn_model.fit(X, Y)

# siatka 2D
x_min, x_max = X_pca[:, 0].min() - 1, X_pca[:, 0].max() + 1
y_min, y_max = X_pca[:, 1].min() - 1, X_pca[:, 1].max() + 1

xx, yy = np.meshgrid(
    np.linspace(x_min, x_max, 100),
    np.linspace(y_min, y_max, 100)
)

# konwersja 2D → 4D
grid_2D = np.c_[xx.ravel(), yy.ravel()]
grid_4D = pca.inverse_transform(grid_2D)

# predykcja
Z = knn_model.predict(grid_4D)
Z = Z.reshape(xx.shape)

# wykres
plt.figure(figsize=(7,5))

plt.contourf(xx, yy, Z, cmap="viridis", alpha=0.3)
plt.contour(xx, yy, Z, colors='black')

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=Y, cmap="viridis", edgecolor='k')

plt.title("Granica separacji KNN (iris + PCA)")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.show()

# Zadanie nr 5

# dane
X, y = datasets.make_regression(
    n_samples=100,
    n_features=1,
    noise=20,
    random_state=42
)

# model
knn = KNN(n_neighbors=5)
knn.fit(X, y)

# predykcja do wykresu
X_test = np.linspace(X.min(), X.max(), 200).reshape(-1, 1)
y_pred = knn.predict(X_test)

# wykres
plt.figure(figsize=(7,5))

plt.scatter(X, y, color='blue', label='Dane')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='KNN')

plt.title("KNN regresja")
plt.xlabel("X")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.show()

# MSE
y_pred_train = knn.predict(X)
mse = np.mean((y - y_pred_train) ** 2)

print(f"MSE: {mse:.2f}")

# Zadanie nr 6

from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()

k_values = [1, 3, 5, 7, 9]

print("k | Dokładność LOO")
print("--------------------")

for k in k_values:
    scores = []

    for train_index, test_index in loo.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = Y[train_index], Y[test_index]

        knn = KNN(n_neighbors=k)
        knn.fit(X_train, y_train)

        y_pred = knn.predict(X_test)

        scores.append(y_pred[0] == y_test[0])

    accuracy = np.mean(scores)

    print(f"{k} | {accuracy:.3f}")

# Dla małych wartości k model jest bardzo wrażliwy na szum i może przeuczać
# dane (overfitting). Dla dużych k model uśrednia zbyt wiele punktów,
# co prowadzi do niedouczenia (underfitting).

# Zadanie nr 7

knn_brute = KNN(n_neighbors=3, use_KDTree=False)
knn_brute.fit(X, Y)
pred_brute = knn_brute.predict(X)

knn_tree = KNN(n_neighbors=3, use_KDTree=True)
knn_tree.fit(X, Y)
pred_tree = knn_tree.predict(X)

print(f"Implementacja jest poprawna? {np.array_equal(pred_brute, pred_tree)}")

# kD-drzewo to struktura danych dzieląca przestrzeń na regiony,
# co pozwala szybciej wyszukiwać najbliższych sąsiadów w porównaniu
# do pełnego przeszukiwania wszystkich punktów.

# Zadanie nr 8

import time

sizes = [100, 500, 1000, 2000]

times_brute = []
times_tree = []

for n in sizes:
    X, y = datasets.make_classification(
        n_samples=n,
        n_features=2,
        n_informative=2,
        n_redundant=0,
        random_state=42
    )

    knn_brute = KNN(n_neighbors=5, use_KDTree=False)
    knn_tree = KNN(n_neighbors=5, use_KDTree=True)

    knn_brute.fit(X, y)
    knn_tree.fit(X, y)

    # brute
    start = time.time()
    knn_brute.predict(X)
    times_brute.append(time.time() - start)

    # KDTree
    start = time.time()
    knn_tree.predict(X)
    times_tree.append(time.time() - start)

# wykres
plt.figure(figsize=(7,5))

plt.plot(sizes, times_brute, marker='o', label='Brute force')
plt.plot(sizes, times_tree, marker='o', label='KDTree')

plt.xlabel('Liczba próbek (n)')
plt.ylabel('Czas [s]')
plt.title('Porównanie czasu działania KNN')
plt.legend()
plt.grid(True)
plt.show()

# Dla małych zbiorów różnica czasu działania między metodami jest niewielka,
# jednak dla większych zbiorów KDTree zaczyna znacząco przyspieszać
# wyszukiwanie sąsiadów, ograniczając liczbę sprawdzanych punktów.
# Dzieje się tak przy około 1000 próbek.

# Zadanie nr 9

from sklearn.model_selection import KFold

# dane
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/refs/heads/master/BostonHousing.csv")

X = df.drop(columns=['medv']).values
y = df['medv'].values

kf = KFold(n_splits=10, shuffle=True, random_state=42)

k_values = [1, 3, 5, 7, 9]

print("k | MSE (mean +/- std)")
print("------------------------")

for k in k_values:
    mse_scores = []

    for train_idx, test_idx in kf.split(X):

        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        knn = KNN(n_neighbors=k)
        knn.fit(X_train, y_train)

        y_pred = knn.predict(X_test)

        mse = np.mean((y_pred - y_test) ** 2)
        mse_scores.append(mse)

    mean = np.mean(mse_scores)
    std = np.std(mse_scores)

    print(f"{k} | {mean:.2f} +/- {std:.2f}")

# Zadanie nr 10

import time
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

# -------- IRIS --------
iris = datasets.load_iris()
X_iris = iris.data
Y_iris = iris.target

# mój
knn_my = KNN(n_neighbors=5)
knn_my.fit(X_iris, Y_iris)

start = time.time()
pred_my = knn_my.predict(X_iris)
time_my = time.time() - start
acc_my = np.mean(pred_my == Y_iris)

# sklearn
knn_sk = KNeighborsClassifier(n_neighbors=5)
knn_sk.fit(X_iris, Y_iris)

start = time.time()
pred_sk = knn_sk.predict(X_iris)
time_sk = time.time() - start
acc_sk = np.mean(pred_sk == Y_iris)

print("IRIS (klasyfikacja)")
print("Model        | Accuracy | Czas [s]")
print("------------------------------------")
print(f"KNN (my)     | {acc_my:.3f}   | {time_my:.5f}")
print(f"KNN (sk)     | {acc_sk:.3f}   | {time_sk:.5f}")

# -------- BOSTON --------
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/refs/heads/master/BostonHousing.csv")

X_boston = df.drop(columns=['medv']).values
y_boston = df['medv'].values

# mój
knn_my = KNN(n_neighbors=5)
knn_my.fit(X_boston, y_boston)

start = time.time()
pred_my = knn_my.predict(X_boston)
time_my = time.time() - start
mse_my = np.mean((pred_my - y_boston)**2)

# sklearn
knn_sk = KNeighborsRegressor(n_neighbors=5)
knn_sk.fit(X_boston, y_boston)

start = time.time()
pred_sk = knn_sk.predict(X_boston)
time_sk = time.time() - start
mse_sk = np.mean((pred_sk - y_boston)**2)

print("\nBOSTON (regresja)")
print("Model        | MSE    | Czas [s]")
print("----------------------------------")
print(f"KNN (my)     | {mse_my:.2f} | {time_my:.5f}")
print(f"KNN (sk)     | {mse_sk:.2f} | {time_sk:.5f}")